Base de dados "credit_data.csv" disponibilizada pelo curso "Machine Learning e Data Science com Python de A a Z" da Udemy

In [ ]:
import pandas as pd

base = pd.read_csv('credit_data.csv')

In [ ]:
base.describe()

i#clientid        income          age          loan    c#default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

Limpando dados faltantes

In [ ]:
print(base.loc[base['age']<0])

    i#clientid        income        age         loan  c#default
15          16  50501.726689 -28.218361  3977.287432          0
21          22  32197.620701 -52.423280  4244.057136          0
26          27  63287.038908 -36.496976  9595.286289          0


In [ ]:
base.drop(base[base.age < 0].index, inplace=True)

In [ ]:
base

i#clientid        income        age         loan  c#default
0              1  66155.925095  59.017015  8106.532131          0
1              2  34415.153966  48.117153  6564.745018          0
2              3  57317.170063  63.108049  8020.953296          0
3              4  42709.534201  45.751972  6103.642260          0
4              5  66952.688845  18.584336  8770.099235          1
...          ...           ...        ...          ...        ...
1995        1996  59221.044874  48.518179  1926.729397          0
1996        1997  69516.127573  23.162104  3503.176156          0
1997        1998  44311.449262  28.017167  5522.786693          1
1998        1999  43756.056605  63.971796  1622.722598          0
1999        2000  69436.579552  56.152617  7378.833599          0

[1997 rows x 5 columns]

In [ ]:
base = pd.read_csv('credit_data.csv')

In [ ]:
base.mean

<bound method DataFrame.mean of       i#clientid        income        age         loan  c#default
0              1  66155.925095  59.017015  8106.532131          0
1              2  34415.153966  48.117153  6564.745018          0
2              3  57317.170063  63.108049  8020.953296          0
3              4  42709.534201  45.751972  6103.642260          0
4              5  66952.688845  18.584336  8770.099235          1
...          ...           ...        ...          ...        ...
1995        1996  59221.044874  48.518179  1926.729397          0
1996        1997  69516.127573  23.162104  3503.176156          0
1997        1998  44311.449262  28.017167  5522.786693          1
1998        1999  43756.056605  63.971796  1622.722598          0
1999        2000  69436.579552  56.152617  7378.833599          0

[2000 rows x 5 columns]>

Tratamento de dados faltantes com a média

In [ ]:
base['age'].mean()

40.80755937840458

In [ ]:
base['age'][base.age>0].mean()

40.92770044906149

In [ ]:
base.loc[base.age < 0,'age'] = base['age'][base.age>0].mean()

In [ ]:
base['age'].mean()

40.927700449062115

In [ ]:
print(base.loc[base['age']<0])

Empty DataFrame
Columns: [i#clientid, income, age, loan, c#default]
Index: []


In [ ]:
pd.isnull(base['age'])

0       False
1       False
2       False
3       False
4       False
        ...  
1995    False
1996    False
1997    False
1998    False
1999    False
Name: age, Length: 2000, dtype: bool

In [ ]:
base.loc[pd.isnull(base['age'])]

i#clientid        income  age         loan  c#default
28          29  59417.805406  NaN  2082.625938          0
30          31  48528.852796  NaN  6155.784670          0
31          32  23526.302555  NaN  2862.010139          0

In [ ]:
previsor = base.iloc[:, 1:4].values

In [ ]:
previsor

array([[6.61559251e+04, 4.09277004e+01, 8.10653213e+03],
       [3.44151540e+04, 4.09277004e+01, 6.56474502e+03],
       [5.73171701e+04, 4.09277004e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 4.09277004e+01, 5.52278669e+03],
       [4.37560566e+04, 4.09277004e+01, 1.62272260e+03],
       [6.94365796e+04, 4.09277004e+01, 7.37883360e+03]])

In [ ]:
classe = base.iloc[: , 4].values

In [ ]:
classe

array([0, 0, 0, ..., 1, 0, 0])

In [ ]:
from sklearn.impute import SimpleImputer
import numpy as np

In [ ]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')


In [ ]:
imputer = imputer.fit(previsor[:, 0:3])

In [ ]:
previsor[:, 0:3] = imputer.transform(previsor[: , 0:3])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsor = scaler.fit_transform(previsor)

In [ ]:
previsor

array([[ 1.45393393,  0.        ,  1.20281942],
       [-0.76217555,  0.        ,  0.69642695],
       [ 0.83682073,  0.        ,  1.17471147],
       ...,
       [-0.07122592,  0.        ,  0.35420081],
       [-0.11000289,  0.        , -0.92675625],
       [ 1.682986  ,  0.        ,  0.96381038]])